--SELECT PRODUCT WITH HIGHEST REVENUE  PER PRODUCT CATEGORY AND STORE LOCATION
SELECT DISTINCT PRODUCT_CATEGORY, PRODUCT_TYPE,PRODUCT_DETAIL,STORE_LOCATION,
SUM(TRANSACTION_QTY * CAST (REPLACE (UNIT_PRICE, ',', '.') AS FLOAT)) AS HIGHEST_REVENUE
FROM COFFEE_SALES
GROUP BY ALL
ORDER BY HIGHEST_REVENUE DESC;

SELECT * FROM COFFEE_SALES;

-- CHECKING MIN AND MAX UNIT PRICE
SELECT UNIT_PRICE, MAX(UNIT_PRICE) FROM COFFEE_SALES
GROUP BY UNIT_PRICE
ORDER BY UNIT_PRICE DESC;

--CHECKING TRADING HOURS 

SELECT MIN(TRANSACTION_TIME) FROM COFFEE_SALES;
SELECT MAX(TRANSACTION_TIME) FROM COFFEE_SALES;

-- HIGHEST AND LOWEST PERFORMING PRODUCT- SALES TRENDS

SELECT 
  PRODUCT_CATEGORY,
  SUM(TO_NUMBER(REPLACE(UNIT_PRICE, ',', '.'))) AS total_revenue
FROM 
  COFFEE_SALES
GROUP BY 
  PRODUCT_CATEGORY
ORDER BY 
  total_revenue DESC;

SELECT MAX(PRODUCT_CATEGORY) FROM COFFEE_SALES;



--CREATING TIME BUCKETS PER STORE LOCATION
SELECT DISTINCT STORE_LOCATION,
CASE 
    WHEN TO_TIME(TRANSACTION_TIME)  BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '17:00:00' AND '20:59:32' THEN 'EVENING'
    ELSE 'NIGHT'
END AS TIME_BUCKET FROM COFFEE_SALES;

-- WHAT TIME DOES EACH STORE PERFORM BEST
SELECT COUNT (DISTINCT TRANSACTION_ID) NUMBER_OF_SALES,
PRODUCT_CATEGORY,
PRODUCT_DETAIL,
PRODUCT_TYPE,
STORE_LOCATION,

CASE 
    WHEN TO_TIME(TRANSACTION_TIME)  BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '17:00:00' AND '20:59:32' THEN 'EVENING'
    ELSE 'NIGHT'
END AS TIME_BUCKET FROM COFFEE_SALES
GROUP BY ALL;

--- TOP PERFORMING ITEMS BY SALES
SELECT COUNT(TRANSACTION_ID) AS NUMBER_OF_SALES, PRODUCT_CATEGORY,PRODUCT_DETAIL,PRODUCT_TYPE,STORE_LOCATION,
CASE
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '06:00:00' AND '11:59:59' THEN 'MORNING'
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '12:00:00' AND '16:59:59' THEN 'AFTERNOON'
    WHEN TO_TIME(TRANSACTION_TIME) BETWEEN '17:00:00' AND '20:59:59' THEN 'EVENING'
    ELSE 'NIGHT'
END AS TIME_BUCKET FROM COFFEE_SALES
GROUP BY ALL
ORDER BY NUMBER_OF_SALES DESC;
    
SELECT * FROM COFFEE_SALES;

--30MIN TIME INTERVALS
SELECT 
  DATEADD(
    MINUTE,
    FLOOR(DATE_PART(MINUTE,TRANSACTION_TIME) / 30) * 30,
    DATE_TRUNC('HOUR', TRANSACTION_TIME)
  ) AS interval_start,
  COUNT(*) AS TOTAL_SALES
FROM COFFEE_SALES
GROUP BY interval_start
ORDER BY interval_start;

SELECT MAX (TRANSACTION_DATE)
FROM COFFEE_SALES;
